# Generated by Django 5.1.1 on 2024-10-02 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=10, null=True, unique=True)),
                ('father_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('essential_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('shaba_namber', models.CharField(blank=True, max_length=24, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('upload_photo_of_national_card_from_file', models.ImageField(blank=True, null=True, upload_to='national_card/')),
                ('upload_profile_picture_from_file', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.permission')),
            ],
        ),
    ]
