<<<<<<< HEAD
# Generated by Django 5.1.1 on 2024-10-27 09:14
=======
# Generated by Django 5.1.1 on 2024-10-02 07:01
>>>>>>> 261e643f41a1a5280e7867d74b276d56f5fe6f17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('auth', '0012_alter_user_first_name_max_length'),
>>>>>>> 261e643f41a1a5280e7867d74b276d56f5fe6f17
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('essential', 'ضروری'), ('normal', 'معمولی')], max_length=20)),
                ('request_type', models.CharField(choices=[('renewal', 'تمدید وام'), ('new', 'درخواست جدید')], max_length=7)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(default='2024-01-01')),
                ('installment_number', models.PositiveSmallIntegerField(default=0)),
                ('total_deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rank', models.PositiveSmallIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='بدون عنوان', max_length=255)),
                ('message_to_manager', models.TextField(default='')),
                ('manager_message', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('guarantor_request_message', models.TextField(blank=True, null=True)),
                ('guarantor_rejection_message', models.TextField(blank=True, null=True)),
                ('manager_description', models.TextField(blank=True, null=True)),
                ('ticket_priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد')], default='medium', max_length=6)),
                ('message_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(default='', max_length=15)),
                ('emergency_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('national_code', models.CharField(default='', max_length=10)),
                ('card_number', models.CharField(default='0', max_length=16)),
                ('shaba_number', models.CharField(default='', max_length=24)),
                ('card_picture', models.ImageField(blank=True, null=True, upload_to='card_pictures/')),
                ('admin_card_info', models.TextField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('user_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('pending_messages', models.TextField(blank=True, null=True)),
                ('send_message_field', models.TextField(blank=True, null=True)),
                ('admin_message_notes', models.TextField(blank=True, null=True)),
                ('reminder', models.CharField(blank=True, max_length=255, null=True)),
                ('allowed_guarantors_count', models.PositiveIntegerField(default=0)),
                ('withdrawal_operation', models.BooleanField(default=False)),
                ('search_field', models.JSONField(blank=True, null=True)),
                ('home_phone', models.CharField(default='بدون شماره', max_length=15)),
                ('national_id_picture', models.ImageField(default='path/to/default/image.jpg', upload_to='national_ids/')),
                ('profile_picture', models.ImageField(default='path/to/default/image.jpg', upload_to='profiles/')),
                ('guarantor_search', models.JSONField(blank=True, null=True)),
                ('withdraw_from_fund', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='بدون عنوان', max_length=300)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('unpaid', 'پرداخت نشده')], default='pending', max_length=10)),
                ('manager_approval', models.BooleanField(default=False)),
                ('receipt_upload', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('deposit_status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit_date', models.DateTimeField(blank=True, null=True)),
                ('receipt_date', models.DateTimeField(blank=True, null=True)),
                ('six_month_chart_data', models.JSONField(blank=True, null=True)),
                ('fund_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_installments', models.PositiveIntegerField(default=0)),
                ('unpaid_installments', models.PositiveIntegerField(default=0)),
                ('payment_statement', models.TextField(blank=True, null=True)),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subscription_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('allowed_loans_count', models.PositiveIntegerField(default=0)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('has_paid_this_month', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
=======
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=10, null=True, unique=True)),
                ('father_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('essential_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('shaba_namber', models.CharField(blank=True, max_length=24, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('upload_photo_of_national_card_from_file', models.ImageField(blank=True, null=True, upload_to='national_card/')),
                ('upload_profile_picture_from_file', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.permission')),
>>>>>>> 261e643f41a1a5280e7867d74b276d56f5fe6f17
            ],
        ),
    ]
