# Generated by Django 5.1.1 on 2024-10-30 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('short', 'کوتاه\u200cمدت'), ('long', 'بلندمدت')], default='short', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message_to_manager', models.TextField()),
                ('manager_message', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('guarantor_request_message', models.TextField(blank=True, null=True)),
                ('guarantor_rejection_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('manager_description', models.TextField(blank=True, null=True)),
                ('ticket_priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد')], default='medium', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='app_mehr.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('short', 'کوتاه\u200cمدت'), ('long', 'بلندمدت')], max_length=10)),
                ('request_type', models.CharField(choices=[('new', 'درخواست جدید'), ('renewal', 'تمدید وام')], max_length=10)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('emergency_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('national_code', models.CharField(max_length=10)),
                ('card_number', models.CharField(max_length=16)),
                ('shaba_number', models.CharField(max_length=24)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('card_picture', models.ImageField(blank=True, null=True, upload_to='card_pictures/')),
                ('national_id_picture', models.ImageField(blank=True, null=True, upload_to='national_ids/')),
                ('admin_card_info', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('national_id', models.CharField(blank=True, max_length=10, null=True)),
                ('guarantor_search', models.CharField(blank=True, max_length=255, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('user_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('pending_messages', models.TextField(blank=True, null=True)),
                ('send_message_field', models.TextField(blank=True, null=True)),
                ('admin_message_notes', models.TextField(blank=True, null=True)),
                ('reminder', models.CharField(blank=True, max_length=255, null=True)),
                ('allowed_guarantors_count', models.PositiveIntegerField(default=0)),
                ('withdrawal_operation', models.BooleanField(default=False)),
                ('search_field', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('deposit_status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit_date', models.DateTimeField(blank=True, null=True)),
                ('receipt_date', models.DateTimeField(blank=True, null=True)),
                ('six_month_chart_data', models.JSONField(blank=True, null=True)),
                ('fund_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_installments', models.PositiveIntegerField(default=0)),
                ('unpaid_installments', models.PositiveIntegerField(default=0)),
                ('payment_statement', models.TextField(blank=True, null=True)),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subscription_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('allowed_loans_count', models.PositiveIntegerField(default=0)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('has_paid_this_month', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
