# Generated by Django 5.1.1 on 2024-10-05 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mehr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='essential_contact_number',
            new_name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='home_phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shaba_namber',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='upload_photo_of_national_card_from_file',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='upload_profile_picture_from_file',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_card_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_message_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='allowed_guarantors_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_number',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_picture',
            field=models.ImageField(blank=True, null=True, upload_to='card_pictures/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='national_id_picture',
            field=models.ImageField(blank=True, null=True, upload_to='national_ids/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pending_messages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reminder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='search_field',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='send_message_field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='shaba_number',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='withdrawal_operation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('essential', 'ضروری'), ('normal', 'معمولی')], max_length=20)),
                ('request_type', models.CharField(choices=[('renewal', 'تمدید وام'), ('new', 'درخواست جدید')], max_length=7)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('deposit_status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit_date', models.DateTimeField(blank=True, null=True)),
                ('receipt_date', models.DateTimeField(blank=True, null=True)),
                ('six_month_chart_data', models.JSONField(blank=True, null=True)),
                ('fund_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_installments', models.PositiveIntegerField(default=0)),
                ('unpaid_installments', models.PositiveIntegerField(default=0)),
                ('payment_statement', models.TextField(blank=True, null=True)),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subscription_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('allowed_loans_count', models.PositiveIntegerField(default=0)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('has_paid_this_month', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
