# Generated by Django 5.1.1 on 2024-11-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mehr', '0002_loanrequest_amount_requested_message_message_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sandogh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('card_number', models.CharField(max_length=16)),
            ],
        ),
    ]
