# Generated by Django 5.1.1 on 2024-10-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mehr', '0002_rename_essential_contact_number_profile_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='due_date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='installment_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='rank',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='total_deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='message',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='guarantor_rejection_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='guarantor_request_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='manager_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='manager_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_to_manager',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='ticket_priority',
            field=models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد')], default='medium', max_length=6),
        ),
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(default='بدون عنوان', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='guarantor_search',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='home_phone',
            field=models.CharField(default='بدون شماره', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='withdraw_from_fund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trans',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trans',
            name='manager_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trans',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trans',
            name='receipt_upload',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='trans',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('unpaid', 'پرداخت نشده')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='trans',
            name='title',
            field=models.CharField(default='بدون عنوان', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_id_picture',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='national_ids/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='profiles/'),
        ),
    ]
