# Generated by Django 5.1.1 on 2024-11-09 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mehr', '0003_sandogh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandogh',
            name='card_number',
        ),
        migrations.CreateModel(
            name='SandoghCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(default='', max_length=150)),
                ('card_number', models.CharField(max_length=16)),
                ('sandogh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_mehr.sandogh')),
            ],
        ),
    ]
