# Generated by Django 5.1.1 on 2024-10-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mehr', '0003_loanrequest_due_date_loanrequest_installment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trans',
            name='title',
            field=models.CharField(default='بدون عنوان', max_length=300),
        ),
    ]
