# Generated by Django 5.1.1 on 2024-10-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mehr', '0004_alter_trans_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='installment_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='rank',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
